version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run :
          name: Install Repository
          command: |
            sudo add-apt-repository universe
            sudo apt update
      -  run:
          name: Install Easy Install
          command: sudo apt-get install python-pip
      - run:
          name: Install PIP
          command: sudo easy_install pip
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli --upgrade --user
            sudo apt-get install awscli
      - run:
          name: Deploy App
          command: |
            npm run backend:deploy
            npm run frontend:deploy
workflows:
  contacts:
    jobs:
      - build
      - deploy